// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdigMUNvNEe2negzxzUokkgFJJn0wmGo',
    appId: '1:99513116167:web:c1bc122b9e3b4e97726ca2',
    messagingSenderId: '99513116167',
    projectId: 'cu-connect-b6ffc',
    authDomain: 'cu-connect-b6ffc.firebaseapp.com',
    storageBucket: 'cu-connect-b6ffc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Mgy-detaq7tDFlFNLC5s04w3cZNgEac',
    appId: '1:99513116167:android:739b7fa460288d55726ca2',
    messagingSenderId: '99513116167',
    projectId: 'cu-connect-b6ffc',
    storageBucket: 'cu-connect-b6ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh187ItXsYfDnfpGvpp_jirGZhf_B4-WU',
    appId: '1:99513116167:ios:2e1957e652091a56726ca2',
    messagingSenderId: '99513116167',
    projectId: 'cu-connect-b6ffc',
    storageBucket: 'cu-connect-b6ffc.appspot.com',
    iosBundleId: 'com.example.cuConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh187ItXsYfDnfpGvpp_jirGZhf_B4-WU',
    appId: '1:99513116167:ios:78db230119897be4726ca2',
    messagingSenderId: '99513116167',
    projectId: 'cu-connect-b6ffc',
    storageBucket: 'cu-connect-b6ffc.appspot.com',
    iosBundleId: 'com.example.cuConnect.RunnerTests',
  );
}
